### ISSUE TITLE
waitForAngularRequestsToFinish error 'asynchronous script timeout: result was not received in 10 seconds"

### ISSUE THREAD

**Issue by d0mu** [paul-hammant/ngWebDriver#79] opened 2019-01-16 16:50 UTC
Hi!

I've been using successfully the call waitForAngularRequestsToFinish() in my tests until December. I've just restarted the project and it doesn't work anymore (same code, same Angular version 5)
I get the error: 'asynchronous script timeout: result was not received in 10 seconds'

Any clue what would be the cause or what to look for - whether if it is the testing framework or the app.

Thanks!

**Comment by d0mu** [comment] 2019-01-18 17:44
Thanks for your reply, Paul.

I'm thinking about a way to share the code with you so you can reproduce the issue. 
It will require to send you credentials via e-mail and to probably to whitelist your IP address. It's an online banking app and it has a 2 factor authentication (cred+ code). Would this be ok with you?

**Comment by paul-hammant** [comment] 2019-01-18 21:46
Nice idea - it may take many many attempts to resolve it that way though, with no guarantees. leaving you org nervous about the whitelisted IP for days at a time.

**Comment by paul-hammant** [comment] 2019-02-19 14:18
@d0mu - how's it going re this ?

**Comment by sudharsan-selvaraj** [comment] 2019-03-05 14:13
@d0mu @paul-hammant  The issue is, if any of the API call made by the application exceeds 10 seconds selenium will throw ScriptTimeOut Error. To increase the wait time of asynchronous scripts, increase the wait time using`driver.manage().timeouts().setScriptTimeout(15, TimeUnit.SECONDS);`. Hope this helps!

**Comment by paul-hammant** [comment] 2019-03-05 14:59
I prefer within() and without() of FluentSelenium, myself :)

**Comment by paul-hammant** [comment] 2019-03-05 15:00
@d0mu ... I'm going to close this issue in the absence of an update from you.

**Closed** 2019-11-18 12:23 UTC
