### ISSUE TITLE
waitForAngular2RequestsToFinish() is non-functional

### ISSUE THREAD

**Issue by vp2** [paul-hammant/ngWebDriver#41] opened 2017-02-27 12:05 UTC
The `waitForAngular2RequestsToFinish` code attempts to load `waitForAllAngular2` client-side helper function, which is missing from protractor's `cliendsidescripts.js`

Was it an intention to implement dedicated Angular2-only wait functionality, or just a typo?

**Comment by paul-hammant** [comment] 2017-02-27 14:54
Missing a test perhaps. That and the likelihood that the Protractor team renamed the method.

**Comment by vp2** [comment] 2017-02-28 12:09
Just a suggestion to wrap `ByAngular.functions.get(...)` into a getter to check for nullity. It will save a lot of time if Protractor team will make any more changes.

**Comment by paul-hammant** [comment] 2017-03-02 19:56
Good thought

**Comment by christian-wojtowicz** [comment] 2017-03-15 10:21
@paul-hammant I would suggest to make the used version of protractor configurable. 
The master one can be default, but it would be good to have an option to set it to a specific one.

At the moment waitForAngular2 is not working, which is really confusing. Such an option would prevent from situation, where the protractor team makes significant changes, which would problems with the ngWebDriver library.

**Comment by paul-hammant** [comment] 2018-03-01 08:26
Pull Requests accepted :)  Closing for now.

**Closed by paul-hammant** 2018-03-01 08:26 UTC

**Comment by andrewg78** [comment] 2018-04-05 11:50
Is there any chance to have this missing waitForAllAngular2 helper fixed soon?
I do not see any commits to master since your last post.

**Comment by andrewg78** [comment] 2018-04-05 18:36
I'm just referring to first post @vp2 
I see waitForAngular2RequestsToFinish still tries to load not existing function.

**Comment by paul-hammant** [comment] 2018-04-05 21:47
So I'm just going to delete `waitForAngular2RequestsToFinish()` then.  The logic has been subsumed into `waitForAngularRequestsToFinish()` which will adapt on the browser side between Angular1 and 2+.

**Comment by paul-hammant** [comment] 2018-04-06 09:16
Can you make me a smallest-possible reproduction on GitHub @andrewg78 ?

**Comment by andrewg78** [comment] 2018-04-06 14:16
I was told we are using Angular 2 components downgraded to Angular 1.
Might this be a reason?
What kind of reproduction you ask for?

**Comment by paul-hammant** [comment] 2018-04-06 14:47
A new repo on Github that I can clone.

It contains at least one HTML that has an Angular app that exhibits the problem.

If you can do this I will charge you $0 for fixing anything that needs fixing and/or advising you.

**Comment by paul-hammant** [comment] 2018-04-18 13:28
waitForAngular2RequestsToFinish() has been deleted in the 1.1.3 release of ngWebDriver
